apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: animales
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
--- 
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: animales
spec:
  selector:
    servicio: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30001
  type: NodePort
